### ISSUE TITLE
push access?

### ISSUE THREAD

**Issue by cdisselkoen** [chicago-relaxed-memory/spec-eval#2]
Hi everyone,

I don't currently have push access to this repo and was wondering if I could be given it?  I'm a "member" of `chicago-relaxed-memory` but that doesn't give me push access to its repos by default.

Thanks!

**Comment by asajeffrey** [comment]
OK, I think you should now have write access. Can you give it a shot?

**Comment by cdisselkoen** [comment]
Works perfect!
